# Generated by Django 2.0.3 on 2018-04-23 18:14

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelUserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic',
                 cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture of user', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Address of user', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth of user')),
                ('user_id',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'hotel User',
                'verbose_name_plural': 'Hotel Users',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Add room image', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Description of the image', max_length=100)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupants', models.IntegerField(help_text='number of people staying')),
                ('check_in_date', models.DateTimeField(help_text='Date of check in')),
                ('check_out_date', models.DateTimeField(help_text='Date of check out')),
                ('payment', models.IntegerField(help_text='total expense of rooms')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to='polls.HotelUserProfile')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Registration')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Registration Detail',
                'verbose_name_plural': 'Registration Details',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('review', models.CharField(blank=True, help_text='Review description', max_length=200)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(help_text='Enter the room number')),
                ('status',
                 models.CharField(blank=True, choices=[('o', 'Occupied'), ('a', 'Available'), ('r', 'Reserved')],
                                  help_text='room availability', max_length=1)),
            ],
            options={
                'ordering': ['room_number'],
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Type name of the room', max_length=50)),
                ('capacity', models.IntegerField(help_text='Number of people that can stay')),
                ('price', models.IntegerField(help_text='Price for one night')),
                ('description', models.CharField(blank=True, help_text='Description of the room', max_length=200)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_dryer', models.BooleanField(default=False)),
                ('has_room_service', models.BooleanField(default=False)),
                ('has_breakfast', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_spa', models.BooleanField(default=False)),
                ('has_mini_bar', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_electronic_safe', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Type'),
        ),
        migrations.AddField(
            model_name='review',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Room'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='polls.HotelUserProfile'),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Room'),
        ),
        migrations.AddField(
            model_name='images',
            name='room_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Type'),
        ),
    ]
