# Generated by Django 2.0.3 on 2018-04-24 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteluserprofile',
            name='date_of_birth',
        ),
    ]
