# Generated by Django 2.0.3 on 2018-04-24 04:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_remove_hoteluserprofile_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelUserProfile',
            new_name='Profile',
        ),
    ]
