# Generated by Django 2.0.3 on 2018-04-24 06:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0003_auto_20180424_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True,
                                                    default='http://res.cloudinary.com/dfl4tcmei/image/upload/v1524552656/empty_profile.png',
                                                    help_text='Profile picture of user', max_length=255),
        ),
    ]
