# Generated by Django 2.0.3 on 2018-04-27 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0004_auto_20180424_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='room_id',
        ),
    ]
