# Generated by Django 2.0.3 on 2018-04-27 18:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0005_remove_review_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 27, 23, 36, 57, 590166)),
        ),
    ]
