# Generated by Django 2.0.3 on 2018-04-27 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0006_review_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
