# Generated by Django 2.0.3 on 2018-04-28 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0007_auto_20180427_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['rating', 'review_date'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
